GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name" : "adwitya",
    "age" : "23",
    "gender" : "Male",
    "hobby" : "Coding",
    "contact" : "082257367240"
}

###
GET http://localhost:5000/api/users/65bbbbc11bcaabee4a72f0f8

###
PATCH http://localhost:5000/api/users/65bbbb42f0acdbbcd0ca1e7d
Content-Type: application/json

{
    "name" : "indah",
    "age" : "23",
    "gender" : "Male",
    "hobby" : "Coding",
    "contact" : "082257367240"
}

### 
DELETE http://localhost:5000/api/users/65bbba263cd0f4b852622db0